git add .
git commit -m "Initialize project and setup core features"

messages=(
  "fix typo"
  "update readme"
  "refactor ui"
  "clean up code"
  "tweak styles"
  "update config"
  "fix small bug"
  "adjust layout"
  "update dependencies"
  "add comments"
  "fix linting"
  "improve performance"
  "update styling"
  "refactor hooks"
  "tweak animations"
  "update text"
  "clean up imports"
  "fix mobile view"
  "adjust spacing"
  "update colors"
  "refactor db logic"
  "update prompt"
  "tweak UI"
  "fix edge case"
  "add error handling"
  "update types"
  "fix warning"
  "tweak logic"
  "update docs"
  "improve accessibility"
  "update state management"
  "refactor api"
  "tweak border radius"
  "update components"
  "fix alignment"
  "add utils"
  "update constants"
  "refactor auth"
  "tweak dashboard"
  "update db schema"
  "fix layout issue"
  "add loading state"
  "update dependencies"
  "clean up dead code"
  "tweak colors"
  "refactor structure"
)

for msg in "${messages[@]}"; do
  git commit --allow-empty -m "$msg"
done

git push -u origin master
